version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - my-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - my-network

networks:
  my-network: