[tool.poetry]
name = "backend"
version = "0.1.0"
description = "Backend for VAE"
authors = ["Lionel Guillou <lionel.guillou@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
